---
apiVersion: v2
name: orca-chart
description: Varnish Orca Helm chart
type: application
version: 0.2.0
appVersion: 0.10.0
maintainers:
  - email: containers@varnish-software.com
    name: Varnish Software
