{{- if .Values.ui.ingress.enabled }}
{{- if (not (and (.Values.ui.service.enabled) (.Values.ui.service.port))) }}
{{ fail "UI service must be enabled in values to enable ingress: 'ui.service.port'" }}
{{- end }}
{{- $serviceName := printf "%s-%s" (include "varnish-controller.fullname" .) "ui" }}
{{- $servicePort := .Values.ui.service.port }}
{{- $pathType := .Values.ui.ingress.pathType }}
{{- $kubeVersion := .Capabilities.KubeVersion.Version }}
{{- if semverCompare ">= 1.19.0-0" $kubeVersion }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "varnish-controller.fullname" . }}-ui
  labels:
    {{- include "varnish-controller.labels" (merge (dict "nameSuffix" "ui") .) | nindent 4 }}
    {{- include "varnish-controller.ingressLabels" (merge (dict "section" "ui") .) | indent 4 }}
  {{- include "varnish-controller.ingressAnnotations" (merge (dict "section" "ui") .) | indent 2 }}
spec:
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{- range .Values.ui.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ui.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            {{- if semverCompare ">= 1.19.0-0" $kubeVersion }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">= 1.19.0-0" $kubeVersion }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
