{{- if .Values.secretCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: varnish-controller-credentials
  labels:
    {{- include "varnish-controller.labels" . | nindent 4 }}
data:
{{- $oldSecret := lookup "v1" "Secret" .Release.Namespace "varnish-controller-credentials" }}
{{- if and .Values.nats.enabled (or (and (eq (kindOf .Values.global.natsServer.internal.enabled) "string") (eq .Values.global.natsServer.internal.enabled "-")) .Values.global.natsServer.internal.enabled) }}
  {{- if or (not $oldSecret) (not $oldSecret.data) (not (index $oldSecret.data "nats-varnish-password")) }}
  nats-varnish-password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  nats-varnish-password: {{ index $oldSecret.data "nats-varnish-password" }}
  {{- end }}
{{- end }}
{{- if and .Values.postgresql.enabled (eq .Values.postgresql.auth.existingSecret "varnish-controller-credentials") }}
  {{- if or (not $oldSecret) (not $oldSecret.data) (not (index $oldSecret.data "postgresql-admin-password")) }}
  postgresql-admin-password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  postgresql-admin-password: {{ index $oldSecret.data "postgresql-admin-password" }}
  {{- end }}
  {{- if or (not $oldSecret) (not $oldSecret.data) (not (index $oldSecret.data "postgresql-varnish-password")) }}
  postgresql-varnish-password: {{ randAlphaNum 20 | b64enc }}
  {{- else }}
  postgresql-varnish-password: {{ index $oldSecret.data "postgresql-varnish-password" }}
  {{- end }}
{{- end }}
{{- if eq .Values.brainz.modAdminUser.password "" }}
{{- if or (not $oldSecret) (not $oldSecret.data) (not (index $oldSecret.data "varnish-admin-password")) }}
  varnish-admin-password: {{ randAlphaNum 20 | b64enc }}
{{- else }}
  varnish-admin-password: {{ index $oldSecret.data "varnish-admin-password" }}
{{- end }}
{{- end }}
{{- end }}
