{{- $vclConfig := include "varnish.vclConfig" . }}
{{- $defaultVcl := osBase .Values.server.vclConfigPath }}
{{- if not (eq $vclConfig "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish-cache.fullname" . }}-vcl
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
data:
  {{ $defaultVcl }}: |
    {{- $vclConfig | nindent 4 }}
{{- end }}
{{- $vclConfigs := omit .Values.server.vclConfigs $defaultVcl }}
{{- if not (empty $vclConfigs) }}
{{- range $k, $v := $vclConfigs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish-cache.fullname" $ }}-vcl-{{ regexReplaceAll "\\W+" $k "-" }}
  labels:
    {{- include "varnish-cache.labels" $ | nindent 4 }}
data:
  {{ $k }}: |
    {{- tpl $v $ | nindent 4 }}
{{- end }}
{{- end }}
