{{- if .Values.server.service.enabled -}}
{{- $serviceType := .Values.server.service.type | toString }}
{{- $serviceClusterIP := .Values.server.service.clusterIP | toString }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish-cache.fullname" . }}
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
    {{- include "varnish-cache.serviceLabels" . | indent 4 }}
  {{- include "varnish-cache.serviceAnnotations" . | indent 2 }}
spec:
  {{- if .Values.server.service.type }}
  type: {{ .Values.server.service.type }}
  {{- end }}
  {{- if .Values.server.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.server.service.internalTrafficPolicy }}
  {{- end }}
  {{- if .Values.server.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.server.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.server.service.clusterIP }}
  clusterIP: {{ .Values.server.service.clusterIP }}
  {{- end }}
  ports:
  {{- if .Values.server.service.http.enabled }}
  {{- if (not .Values.server.http.enabled) }}
  {{ fail "HTTP support must be enabled in values to enable HTTP service: 'server.http.enabled'" }}
  {{- else }}
    - name: http
      {{- if and (eq $serviceType "ClusterIP") (eq $serviceClusterIP "None") }}
      port: {{ .Values.server.http.port }}
      {{- else }}
      port: {{ .Values.server.service.http.port }}
      {{- end }}
      targetPort: {{ .Values.server.http.port }}
      {{- if and (.Values.server.service.http.nodePort) (eq $serviceType "NodePort") }}
      nodePort: {{ .Values.server.service.http.nodePort }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- range .Values.server.service.extraServices }}
  {{- if not .name }}
  {{ fail "Name must be set in extraServices: 'server.service.extraServices[].name'" }}
  {{- end }}
  {{- if not .targetPort }}
  {{ fail "Target port must be set in extraServices: 'server.service.extraServices[].targetPort'" }}
  {{- end }}
    - name: extra-{{ .name }}
      {{- if and (eq $serviceType "ClusterIP") (eq $serviceClusterIP "None") }}
      port: {{ .targetPort }}
      {{- else if not .port }}
      {{ fail "Port must be set in extraServices: 'server.service.extraServices[].port'" }}
      {{- else }}
      port: {{ .port }}
      {{- end }}
      targetPort: {{ .targetPort }}
      {{- if and .nodePort (eq $serviceType "NodePort") }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "varnish-cache.selectorLabels" . | nindent 4 }}
{{- end }}
