{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varnish-enterprise.serviceAccountName" . }}
  labels:
    {{- include "varnish-enterprise.labels" . | nindent 4 }}
    {{- include "varnish-enterprise.serviceAccountLabels" . | indent 4 }}
  {{- include "varnish-enterprise.serviceAccountAnnotations" . | indent 2 }}
{{- end }}
