---
apiVersion: v2
name: varnish-enterprise
description: Varnish Enterprise Helm chart
type: application
version: 1.8.4
appVersion: 6.0.18r3
maintainers:
  - email: containers@varnish-software.com
    name: Varnish Software
